stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3.6.2-jdk-8
      shellScript: |-
        mvn clean install
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: demoapp:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 743018426547.dkr.ecr.us-east-1.amazonaws.com/rancher-app-sample/demoapp
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
